### ISSUE TITLE
Problem with set_ts_lo.sh 

### ISSUE THREAD

**Issue by pavan4** [hulu/dripls#2]
I added the user into sudoers list and when I deeply drills it seems to run fine except the shaping. 

```
set_ts_lo.sh seems to exit with return code 1 
```

My interfaces file is like this: 

```
auto lo
iface lo inet loopback
```

I am able to execute the command properly without errors on the terminal. 

Any help for debugging the cause?

**Comment by pavan4** [comment]
I figured out the problem.

**Comment by llaxsll** [comment]
@pavan4 what was the problem? Would be good to share the finding around the setup...
